language: android

jdk:
- oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.3
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

script:
   - ./gradlew build --stacktrace